name 'apache'
maintainer 'Suresh'
maintainer_email 'cheftraining123@example.com'
license 'all_rights'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '0.1.1'
